package api

import (
	"net/http"

	"github.com/gorilla/mux"
	"github.com/jinzhu/gorm"
	docs "github.com/kryptomind/bidboxapi/KeyService/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/kryptomind/bidboxapi/KeyService/middleware"
	httpSwagger "github.com/swaggo/http-swagger"
)

type Server struct {
	DB     *gorm.DB
	Router *mux.Router
}

func (r *Server) InitializeRoutes() {

	docs.SwaggerInfo.Schemes = []string{"https"}

	r.Router.PathPrefix("/docs").Handler(httpSwagger.Handler(
		httpSwagger.URL("http://stg-api-bidbox.kryptomind.net:8080/docs/doc.json"), //The url pointing to API definition
		httpSwagger.DeepLinking(true),
		httpSwagger.DocExpansion("none"),
		httpSwagger.DomID("swagger-ui"),
	)).Methods(http.MethodGet)

	s := r.Router.PathPrefix("/exchanges").Subrouter()
	s.HandleFunc("/", middleware.MiddlewareJSON(r.Home)).Methods("GET")

	// Keys routes
	s.HandleFunc("/keys", middleware.MiddlewareJSON(r.CreateKey)).Methods("POST")
	s.HandleFunc("/keys", middleware.MiddlewareJSON(r.GetKeys)).Methods("GET")
	s.HandleFunc("/keys/{id}", middleware.MiddlewareJSON(r.GetKey)).Methods("GET")
	s.HandleFunc("/supported", middleware.MiddlewareJSON(r.GetExchanges)).Methods("GET")
	s.HandleFunc("/", middleware.MiddlewareJSON(r.CreateExchanges)).Methods("POST")

	// Bitget Data Routes
	s.HandleFunc("/bitget/account", middleware.MiddlewareJSON(r.GetBitgetAccountDetailsData)).Methods("GET")
	s.HandleFunc("/bitget/positions", middleware.MiddlewareJSON(r.GetBitgetOpenPositions)).Methods("GET")
	s.HandleFunc("/bitget/orderHistory", middleware.MiddlewareJSON(r.GetBitgetOrderHistory)).Methods("GET")
	s.HandleFunc("/bitget/historical-positions", middleware.MiddlewareJSON(r.GetBitgetHistoricalPositions)).Methods("GET")

	// Bybit Routes
	s.HandleFunc("/bybit/account", middleware.MiddlewareJSON(r.GetBybitAccountDetails)).Methods("GET")
	s.HandleFunc("/bybit/positions", middleware.MiddlewareJSON(r.GetBybitAccountPositions)).Methods("GET")
	s.HandleFunc("/bybit/closedpnl", middleware.MiddlewareJSON(r.GetBybitCloseProfit_Loss)).Methods("GET")
	//s.HandleFunc("/bybit/orderHistory", middleware.MiddlewareJSON(r.GetBybitOrderHistory)).Methods("GET")

	// Binance Routes
	s.HandleFunc("/binance/account", middleware.MiddlewareJSON(r.GetBinanceAccountDetailsData)).Methods("GET")
	s.HandleFunc("/binance/positions", middleware.MiddlewareJSON(r.GetBinanceAccountPositionsData)).Methods("GET")
	s.HandleFunc("/binance/orderHistory", middleware.MiddlewareJSON(r.GetBinanceOrderHistory)).Methods("GET")
}
